kotlin.code.style=official
dropwizard_version=5.0.0
# Keep this in sync with Dropwizard
metrics_version=4.2.37
# Keep this in sync with Dropwizard
jersey_version=3.1.0
# Keep this in sync with Dropwizard
jackson_version=2.20.1
# Keep this in sync with Dropwizard
liquibase_version=4.33.0
# Keep this in sync with Dropwizard
logback_version=1.5.24

classgraph_version=4.8.184
dropwizard_guicey_version=8.0.0

resilience4j_version=2.3.0

hikari_version=7.0.2

# Testing library versions
test_containers_version=2.0.3
wiremock_version=3.13.2
wiremock_kotlin_version=2.1.1