kotlin.code.style=official
hikari_version=7.0.2
liquibase_logging_version=5.1.0
logback_version=1.5.21
classgraph_version=4.8.184
resilience4j_version=2.3.0
jackson_version=2.20.0
dropwizard_version=5.0.0
dropwizard_guicey_version=8.0.0

# Testing library versions
test_containers_version=2.0.2
wiremock_version=3.13.2
wiremock_kotlin_version=2.1.1