port=8080
adminPort=8081
requestThreads=5
maxQueuedRequests=10

consoleLoggingLevel=OFF
fileLoggingLevel=INFO
logFileArchiveCount=7

database.type=MySQL
database.host=localhost
database.port=3306
database.schema=wc3_bot

refreshInterval=10_000