[libraries]
kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:2.1.0"
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.1"
guice = "dev.misfitlabs.kotlinguice4:kotlin-guice:3.0.0"
guava = "com.google.guava:guava:32.0.1-jre" # Guava brought in by Guice has a vulnerability, so we exclude Guava from Guice, and bring in the newer Guava with the vulnerability fix.
drivers-mariadb = "org.mariadb.jdbc:mariadb-java-client:3.5.1"
drivers-mysql = "com.mysql:mysql-connector-j:9.1.0"
jdbi = "org.jdbi:jdbi3-core:3.47.0"
liquibase = "org.liquibase:liquibase-core:4.30.0"

# Testing Libraries
junit = "org.junit.jupiter:junit-jupiter-api:5.11.4"
assertj = "org.assertj:assertj-core:3.27.2"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.4.0"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:2.1.0"